import { ToolDefinition, AgentIdeRecord, IncidentRecord } from '../types/ide';

export const DEFAULT_TOOLS: ToolDefinition[] = [
  {
    name: 'search_documents',
    description: 'Searches internal knowledge base, PDFs, and documentation vector store.',
    category: 'Information Retrieval',
    risk_level: 'SAFE',
    allowed_roles: ['researcher', 'analyst', 'planner', 'coder'],
    requires_approval: false,
    schema: { query: 'string (min: 2, max: 200)', top_k: 'integer (1..20)' },
    is_sensitive: false,
    canary_monitored: false,
  },
  {
    name: 'read_public_file',
    description: 'Reads verified public files within the designated sandbox volume.',
    category: 'Filesystem',
    risk_level: 'LOW',
    allowed_roles: ['researcher', 'coder', 'analyst'],
    requires_approval: false,
    schema: { path: 'filepath within /sandbox/' },
    is_sensitive: false,
    canary_monitored: false,
  },
  {
    name: 'read_secrets',
    description: 'Accesses encrypted environment credentials and private encryption keys.',
    category: 'Credentials & Vault',
    risk_level: 'CRITICAL',
    allowed_roles: ['security_officer_only'],
    requires_approval: true,
    schema: { secret_name: 'string', reason: 'string' },
    is_sensitive: true,
    canary_monitored: true,
  },
  {
    name: 'execute_code',
    description: 'Executes dynamic code in isolated microVM container with resource quotas.',
    category: 'Code Execution',
    risk_level: 'HIGH',
    allowed_roles: ['admin_coder'],
    requires_approval: true,
    schema: { language: 'python | bash | js', code: 'string', timeout_s: 'number' },
    is_sensitive: true,
    canary_monitored: true,
  },
  {
    name: 'query_database',
    description: 'Executes parameterized SQL queries against production replica read-pool.',
    category: 'Database Access',
    risk_level: 'MEDIUM',
    allowed_roles: ['data_analyst', 'planner'],
    requires_approval: false,
    schema: { query: 'parameterized SQL', params: 'array' },
    is_sensitive: true,
    canary_monitored: false,
  },
  {
    name: 'send_external_request',
    description: 'Transmits egress HTTP payload to external domains outside the perimeter mesh.',
    category: 'Networking & Egress',
    risk_level: 'HIGH',
    allowed_roles: ['admin_integrator'],
    requires_approval: true,
    schema: { url: 'https URL', method: 'GET | POST', body: 'json' },
    is_sensitive: true,
    canary_monitored: true,
  },
];

export const DEFAULT_INCIDENTS: IncidentRecord[] = [
  {
    incident_id: 'INC-2026-091',
    severity: 'CRITICAL',
    agent_id: 'crawler-03',
    title: 'Deception Tripwire Canary Breach',
    description: 'Agent crawler-03 touched /etc/secrets/aws_canary_key. Irreversible quarantine triggered within 0.12ms.',
    timestamp: Date.now() - 1000 * 60 * 18,
    status: 'CONTAINED',
    tripwire_token: 'CANARY_AWS_AKIA_DECEPTION_4491',
    trace_id: 'TRC-CANARY-091',
    rule_violated: 'POL-001 (Honey Deception Tripwire)',
    containment_action: 'Agent circuit breaker tripped to QUARANTINED. Ephemeral epoch bumped.',
  },
  {
    incident_id: 'INC-2026-084',
    severity: 'HIGH',
    agent_id: 'researcher-01',
    title: 'Path Traversal Root Escape Attempt',
    description: 'Attempted to read relative traversal path ../../etc/shadow outside authorized sandbox.',
    timestamp: Date.now() - 1000 * 60 * 45,
    status: 'RESOLVED',
    trace_id: 'TRC-TRAV-084',
    rule_violated: 'POL-002 (Filesystem Directory Traversal)',
    containment_action: 'Immediate Stage-Gate 4 hard block. Zero post-block execution verified.',
  },
  {
    incident_id: 'INC-2026-072',
    severity: 'MEDIUM',
    agent_id: 'coder-02',
    title: 'Elevated Risk Dynamic Code Execution',
    description: 'Action evaluated with composite risk score of 74 due to raw socket call. Routed to Human Cockpit.',
    timestamp: Date.now() - 1000 * 60 * 120,
    status: 'ACTIVE',
    trace_id: 'TRC-RCE-072',
    rule_violated: 'POL-006 (Code Execution Approval Gate)',
    containment_action: 'Execution suspended pending analyst cryptographic dual-key signature.',
  },
];

export const INITIAL_EXPLORER_TREE = [
  {
    folder: 'agents',
    files: [
      { name: 'researcher.agent', path: 'agents/researcher.agent', type: 'agent' as const, id: 'researcher-01' },
      { name: 'coder.agent', path: 'agents/coder.agent', type: 'agent' as const, id: 'coder-02' },
      { name: 'crawler.agent', path: 'agents/crawler.agent', type: 'agent' as const, id: 'crawler-03' },
      { name: 'executor.agent', path: 'agents/executor.agent', type: 'agent' as const, id: 'executor-04' },
    ],
  },
  {
    folder: 'policies',
    files: [
      { name: 'secrets-policy.cel', path: 'policies/secrets-policy.cel', type: 'policy' as const, id: 'POL-001' },
      { name: 'path-traversal.cel', path: 'policies/path-traversal.cel', type: 'policy' as const, id: 'POL-002' },
      { name: 'quarantine-policy.cel', path: 'policies/quarantine-policy.cel', type: 'policy' as const, id: 'POL-003' },
      { name: 'syscall-blacklist.cel', path: 'policies/syscall-blacklist.cel', type: 'policy' as const, id: 'POL-004' },
      { name: 'sql-injection.cel', path: 'policies/sql-injection.cel', type: 'policy' as const, id: 'POL-005' },
      { name: 'code-execution.cel', path: 'policies/code-execution.cel', type: 'policy' as const, id: 'POL-006' },
      { name: 'capability-boundary.cel', path: 'policies/capability-boundary.cel', type: 'policy' as const, id: 'POL-007' },
      { name: 'risk-threshold.cel', path: 'policies/risk-threshold.cel', type: 'policy' as const, id: 'POL-008' },
    ],
  },
  {
    folder: 'tools',
    files: [
      { name: 'search_documents.tool', path: 'tools/search_documents.tool', type: 'tool' as const, id: 'search_documents' },
      { name: 'read_public_file.tool', path: 'tools/read_public_file.tool', type: 'tool' as const, id: 'read_public_file' },
      { name: 'read_secrets.tool', path: 'tools/read_secrets.tool', type: 'tool' as const, id: 'read_secrets' },
      { name: 'execute_code.tool', path: 'tools/execute_code.tool', type: 'tool' as const, id: 'execute_code' },
      { name: 'query_database.tool', path: 'tools/query_database.tool', type: 'tool' as const, id: 'query_database' },
      { name: 'send_external_request.tool', path: 'tools/send_external_request.tool', type: 'tool' as const, id: 'send_external_request' },
    ],
  },
  {
    folder: 'attacks',
    files: [
      { name: 'prompt-injection.attack', path: 'attacks/prompt-injection.attack', type: 'attack' as const, id: 'scn_prompt_injection' },
      { name: 'secret-access.attack', path: 'attacks/secret-access.attack', type: 'attack' as const, id: 'scn_canary_touch' },
      { name: 'gateway-bypass.attack', path: 'attacks/gateway-bypass.attack', type: 'attack' as const, id: 'scn_quarantine_bypass' },
      { name: 'path-traversal.attack', path: 'attacks/path-traversal.attack', type: 'attack' as const, id: 'scn_path_traversal' },
      { name: 'sql-injection.attack', path: 'attacks/sql-injection.attack', type: 'attack' as const, id: 'scn_sql_injection' },
    ],
  },
  {
    folder: 'incidents',
    files: [
      { name: 'INC-2026-091.incident', path: 'incidents/INC-2026-091.incident', type: 'incident' as const, id: 'INC-2026-091' },
      { name: 'INC-2026-084.incident', path: 'incidents/INC-2026-084.incident', type: 'incident' as const, id: 'INC-2026-084' },
      { name: 'INC-2026-072.incident', path: 'incidents/INC-2026-072.incident', type: 'incident' as const, id: 'INC-2026-072' },
    ],
  },
];
